#!/usr/bin/env bash
# Push vpn-bin to AUR after a GitHub release.
#
# Usage: publish-aur.sh <tag>
# Example: publish-aur.sh v0.1.0
#
# Requires: curl, git, ssh, sha256sum
# Environment: AUR_KEY (SSH private key) or SSH_AUTH_SOCK

set -euo pipefail

TAG="${1:?tag required (e.g. v0.1.0)}"
VERSION="${TAG#v}"
REPO="protibimbok/vpn-tui"
AUR_REPO="ssh://aur@aur.archlinux.org/vpn-bin.git"

need() { command -v "$1" >/dev/null 2>&1 || { echo "required: $1" >&2; exit 1; }; }
need curl
need git
need sha256sum

sha256_of_url() {
  local url=$1
  curl -fsSL "$url" | sha256sum | awk '{print $1}'
}

WORKDIR="$(mktemp -d)"
trap 'rm -rf "${WORKDIR}"' EXIT

if [ -n "${AUR_KEY:-}" ]; then
  KEY_FILE="${WORKDIR}/aur_key"
  printf '%s\n' "${AUR_KEY}" > "${KEY_FILE}"
  chmod 600 "${KEY_FILE}"
  export GIT_SSH_COMMAND="ssh -i ${KEY_FILE} -o StrictHostKeyChecking=accept-new"
fi

SHA_AMD64=$(sha256_of_url "https://github.com/${REPO}/releases/download/${TAG}/vpn_linux_amd64.tar.gz")
SHA_ARM64=$(sha256_of_url "https://github.com/${REPO}/releases/download/${TAG}/vpn_linux_arm64.tar.gz")

git clone "${AUR_REPO}" "${WORKDIR}/vpn-bin"
cd "${WORKDIR}/vpn-bin"

# Generate PKGBUILD + .SRCINFO directly (ubuntu runners have no makepkg).
cat > PKGBUILD <<EOF
# Generated by scripts/publish-aur.sh — do not edit by hand.
pkgname=vpn-bin
pkgver=${VERSION}
pkgrel=1
pkgdesc="TUI for managing Surfshark WireGuard connections"
arch=('x86_64' 'aarch64')
url="https://github.com/${REPO}"
license=('MIT')
depends=('wireguard-tools' 'curl' 'iputils')
provides=('vpn')
conflicts=('vpn')
source_x86_64=("https://github.com/${REPO}/releases/download/v\${pkgver}/vpn_linux_amd64.tar.gz")
source_aarch64=("https://github.com/${REPO}/releases/download/v\${pkgver}/vpn_linux_arm64.tar.gz")
sha256sums_x86_64=('${SHA_AMD64}')
sha256sums_aarch64=('${SHA_ARM64}')

package() {
  install -Dm4755 "\${srcdir}/vpn" "\${pkgdir}/usr/bin/vpn"
  install -Dm644 "\${srcdir}/LICENSE" "\${pkgdir}/usr/share/licenses/vpn/LICENSE"
}
EOF

# pkgname must come after pkgbase metadata (pkgver/pkgrel/sources/etc.).
# Putting pkgname first makes go-srcinfo reject the file:
#   key "pkgver" can not occur after pkgname
cat > .SRCINFO <<EOF
pkgbase = vpn-bin
	pkgdesc = TUI for managing Surfshark WireGuard connections
	pkgver = ${VERSION}
	pkgrel = 1
	url = https://github.com/${REPO}
	arch = x86_64
	arch = aarch64
	license = MIT
	depends = wireguard-tools
	depends = curl
	depends = iputils
	provides = vpn
	conflicts = vpn
	source_x86_64 = https://github.com/${REPO}/releases/download/v${VERSION}/vpn_linux_amd64.tar.gz
	sha256sums_x86_64 = ${SHA_AMD64}
	source_aarch64 = https://github.com/${REPO}/releases/download/v${VERSION}/vpn_linux_arm64.tar.gz
	sha256sums_aarch64 = ${SHA_ARM64}

pkgname = vpn-bin
EOF

git add PKGBUILD .SRCINFO
if git diff --cached --quiet; then
  echo "AUR package already up to date for ${TAG}"
  exit 0
fi

git -c user.name="github-actions[bot]" \
    -c user.email="github-actions[bot]@users.noreply.github.com" \
    commit -m "Update to ${TAG}"
git push origin master

echo "Published vpn-bin ${TAG} to AUR"
